# Generated by Django 3.2.5 on 2023-01-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0058_navigationlinks_is_whitelabel_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=100)),
                ('is_main_site', models.BooleanField(default=False)),
                ('is_every_site', models.BooleanField(default=False)),
                ('is_whitelabel_site', models.BooleanField(default=False)),
            ],
        ),
    ]
