# Generated by Django 3.2.5 on 2023-01-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0059_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='column_name_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='column_name_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='column_name_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='column_name_4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='column_name_5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='column_name_6',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='data',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
