# Generated by Django 3.2.5 on 2023-01-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0060_auto_20230111_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_1', models.CharField(blank=True, default='', max_length=50)),
                ('column_2', models.CharField(blank=True, default='', max_length=50)),
                ('column_3', models.CharField(blank=True, default='', max_length=50)),
                ('column_4', models.CharField(blank=True, default='', max_length=50)),
                ('column_5', models.CharField(blank=True, default='', max_length=50)),
                ('column_6', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='data',
        ),
        migrations.AddField(
            model_name='page',
            name='data',
            field=models.ManyToManyField(blank=True, to='business.PageData'),
        ),
    ]
