# Generated by Django 3.2.5 on 2023-01-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0032_auto_20210729_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
